## Importing Libaries and Data Preparation

In [91]:
# Pandas is used for data manipulation
import pandas as pd
import sklearn
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import train_test_split

In [105]:
# Read in data as pandas dataframe and display first 5 rows
features = pd.read_csv(r'D:\My Documents\GCRF papers\New folder\fbprophet-20220217T133904Z-001\fbprophet\MLP\final-data-edited-nozero-07-01-2023.csv')
features.head(5)

State  Average_avg-Temp  Average-Min Temp  Average-max-temp  \
0  Plateau         21.258682         15.489182         27.028740   
1   Taraba         21.287979         15.765146         26.809448   
2  Plateau         21.341573         16.420537         27.247260   
3  Plateau         21.474099         15.814495         27.124927   
4  Plateau         21.523187         15.900604         27.139937   

   avg-precipitation  avg-windSpeed        pH       Clay       Sand  \
0         107.791667       2.258682  5.833333  29.500000  43.166667   
1         136.270833       1.733292  5.400000  37.833333  35.833333   
2         103.395833       2.258510  6.200000  27.500000  44.500000   
3         111.145833       2.237911  5.300000  30.833333  43.666667   
4         101.750000       2.405010  5.850000  30.000000  48.166667   

        Silt  Crop Yield   Hectare  
0  25.833333    2.603023  1.686768  
1  25.000000    2.389935  2.622656  
2  29.333333    2.603023  1.686768  
3  23.833333    2.603023  1.686768  
4  23.833333    2.603023  1.686768

In [93]:
# One-hot encode categorical features
features = pd.get_dummies(features)
features.replace({False: 0, True: 1}, inplace=True)
features.head(5)

Average_avg-Temp  Average-Min Temp  Average-max-temp  avg-precipitation  \
0         21.258682         15.489182         27.028740         107.791667   
1         21.287979         15.765146         26.809448         136.270833   
2         21.341573         16.420537         27.247260         103.395833   
3         21.474099         15.814495         27.124927         111.145833   
4         21.523187         15.900604         27.139937         101.750000   

   avg-windSpeed        pH       Clay       Sand       Silt  Crop Yield  ...  \
0       2.258682  5.833333  29.500000  43.166667  25.833333    2.603023  ...   
1       1.733292  5.400000  37.833333  35.833333  25.000000    2.389935  ...   
2       2.258510  6.200000  27.500000  44.500000  29.333333    2.603023  ...   
3       2.237911  5.300000  30.833333  43.666667  23.833333    2.603023  ...   
4       2.405010  5.850000  30.000000  48.166667  23.833333    2.603023  ...   

   State_Kebbi  State_Kwara  State_Lagos  State_Ogun  State_Ondo  State_Osun  \
0            0            0            0           0           0           0   
1            0            0            0           0           0           0   
2            0            0            0           0           0           0   
3            0            0            0           0           0           0   
4            0            0            0           0           0           0   

   State_Oyo  State_Plateau  State_Rivers  State_Taraba  
0          0              1             0             0  
1          0              0             0             1  
2          0              1             0             0  
3          0              1             0             0  
4          0              1             0             0  

[5 rows x 34 columns]

In [96]:
# Drop duplicate rows
features2 = features.drop_duplicates()
#Drop features not included after feature selection

features2= features2.drop(['Average_avg-Temp', 'Average-max-temp', 'Clay'], axis = 1)
# Use numpy to convert to arrays
import numpy as np

# Labels are the values we want to predict
labels = np.array(features2['Crop Yield'])

# Remove the labels from the features
# axis 1 refers to the columns
data= features2.drop('Crop Yield', axis = 1)

# Saving feature names for later use
data_list = list(data.columns)

# Convert to numpy array
data = np.array(data)

#### Data Split

In [97]:
# Split the data into training, validation,  and testing sets
train_features, val_test_features, train_labels, val_test_labels = train_test_split(data, labels, test_size = 0.3,
                                                                           shuffle= True, random_state = 0)
X_val, X_test, Y_val, Y_test = train_test_split(val_test_features, val_test_labels, test_size=0.5)
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', Y_test.shape)
print('Validation Features Shape:', X_val.shape)
print('Validation Label Shape:', Y_val.shape)

Training Features Shape: (1142, 30)
Training Labels Shape: (1142,)
Testing Features Shape: (245, 30)
Testing Labels Shape: (245,)
Validation Features Shape: (245, 30)
Validation Label Shape: (245,)


## Model

In [98]:
# RFR Model
import sklearn
from numpy import absolute
from pandas import read_csv
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators = 10, max_depth = 10, min_samples_split = 2, min_samples_leaf = 1)
model.fit(train_features, train_labels)

RandomForestRegressor(max_depth=10, n_estimators=10)

In [99]:
# evaluate an xgboost regression model
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
scores = cross_val_score(model, X_test, Y_test, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
# force scores to be positive
scores = absolute(scores)
print('Mean MAE: %.6f (%.6f)' % (scores.mean(), scores.std()) )


Mean MAE: 0.007857 (0.005465)


#### Predictions on Test Set

In [100]:
from sklearn.metrics import mean_squared_error

predictions = model.predict(X_test)


# Mean Squared Error (MSE)
mse = mean_squared_error(Y_test, predictions)
print('Mean Squared Error (MSE): ', mse)

Mean Squared Error (MSE):  3.3767993829735545e-07


In [101]:
from math import sqrt
rmse = sqrt(mse)
print('Root Mean Absolute Error:', rmse, 'degrees.')

Root Mean Absolute Error: 0.0005811023475235283 degrees.


In [102]:
from sklearn.metrics import mean_absolute_percentage_error
# Mean Squared Error (MSE)
mape = mean_absolute_percentage_error(Y_test, predictions)
print('mean absolute percentage error (MAPE): ', mape)

mean absolute percentage error (MAPE):  0.0031957956278873163


In [103]:
from sklearn.metrics import mean_absolute_error


mae = mean_absolute_error(Y_test, predictions)
print('Mean Absolute Error (MAE): ', mae)

Mean Absolute Error (MAE):  3.950666204103488e-05


In [104]:
y_pred = model.predict(X_test)
print(Y_test[1])
print(predictions[1])

5.487014333
5.487014332999999


#### Save Model

In [43]:
import joblib
filename = 'RF_model-07-01-2023.sav'
joblib.dump(model, filename)

['RF_model-07-01-2023.sav']

In [9]:
import joblib
model = joblib.load('RF_model-07-01-2023.sav')

## Testing

#### Generalisation to unseen set

In [18]:
tt = np.array(X_test.reshape(245,30))

In [21]:
tt = np.array(X_test.reshape(245,30))
pred = model.predict(tt)

In [27]:
tt = np.array(X_test.reshape(245,30))
pred = model.predict(tt)
pred = pd.DataFrame(pred)
yact = pd.DataFrame(Y_test)
all = pd.concat([pred, yact], axis=1)


all.columns = ["y_pred", "y_actual"]
all.to_csv('predictedRF&actual.csv')

#### Generalisation to Unforeseen set

##### change to precipitation

In [10]:
tf = np.array([ 21.69209,   13.52083,     1.4988489,   5.4666667,  59.833332,   10.166667,   0.5454889,   0. ,         0.,          0.,          0.,          0.,   0.,          0.,          0.,          0.,          0.,          0.,1.,          0.,          0.,          0.,          0.,          0.,  0.,          0.,          0.,          0.,          0. ,         0. ])
model.predict(np.array(tf).reshape(1,30))

array([0.70938868])

In [13]:
tf2 = np.array([16.685463 , 9.125 ,     2.417177,   5.5666666 ,35.5   ,    27.333334,  1.6867675,  0.  ,       0.    ,     0. ,        0.         ,0.,  0.  ,       0.   ,      0.   ,      0.   ,      0.   ,      0.,  0.  ,       0.   ,      0.    ,     0.    ,     0.    ,     0.,  0.   ,      0.   ,      0.  ,       1.    ,     0.  ,       0.       ])
model.predict(np.array(tf2).reshape(1,30))

array([2.60302342])

###### change silt

In [12]:
tf = np.array([ 21.69209,   133.52083,     1.4988489,   5.4666667,  59.833332,   29.166667,   0.5454889,   0. ,         0.,          0.,          0.,          0.,   0.,          0.,          0.,          0.,          0.,          0.,1.,          0.,          0.,          0.,          0.,          0.,  0.,          0.,          0.,          0.,          0. ,         0. ])
model.predict(np.array(tf).reshape(1,30))

array([0.70938868])

In [14]:
tf2 = np.array([16.685463 , 99.125 ,     2.417177,   5.5666666 ,35.5   ,    50.333334,  1.6867675,  0.  ,       0.    ,     0. ,        0.         ,0.,  0.  ,       0.   ,      0.   ,      0.   ,      0.   ,      0.,  0.  ,       0.   ,      0.    ,     0.    ,     0.    ,     0.,  0.   ,      0.   ,      0.  ,       1.    ,     0.  ,       0.       ])
model.predict(np.array(tf2).reshape(1,30))

array([2.60302342])